### ISSUE TITLE
Build err

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/frontend-lab#4]
Please provide the following information:

```
frontend-lab git/orderbook-subscriptions  
❯ yarn run dev
```

### Expected behaviour

Err free

### Actual behaviour

```zsh
@melonproject/graphql-server: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run dev
lerna ERR! /home/x3/Melon/frontend-lab/packages/graphql-server/backpack.config.js:16
lerna ERR!       ...carry,
lerna ERR!       ^^^
lerna ERR! 
lerna ERR! SyntaxError: Unexpected token ...
lerna ERR!     at createScript (vm.js:74:10)
lerna ERR!     at Object.runInThisContext (vm.js:116:10)
lerna ERR!     at Module._compile (module.js:533:28)
lerna ERR!     at Object.Module._extensions..js (module.js:580:10)
lerna ERR!     at Module.load (module.js:503:32)
lerna ERR!     at tryModuleLoad (module.js:466:12)
lerna ERR!     at Function.Module._load (module.js:458:3)
lerna ERR!     at Module.require (module.js:513:17)
lerna ERR!     at require (internal/module.js:11:18)
lerna ERR!     at Object.<anonymous> (/home/x3/Melon/frontend-lab/node_modules/backpack-core/bin/dev:18:28)
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ backpack dev
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/x3/Melon/frontend-lab/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
```

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by fubhy** [comment]
You are on an old Node version in that case. Can you upgrade to 8+? Ideally even 9+?
